services:
  db:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
  adminer:
      image: dockette/adminer
      ports:
        - 8080:80
      depends_on:
      - db
