services:
  db:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      
      POSTGRES_PASSWORD: helloWorld1234
      POSTGRES_USER: postgres
  adminer:
      image: dockette/adminer
      ports:
        - 8080:80
      depends_on:
      - db
